# Generated by Django 3.0.6 on 2020-05-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('ordernum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='주문 번호')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문제품',
                'verbose_name_plural': '주문제품',
                'db_table': 'fastcampus_orderItem',
            },
        ),
    ]
