# Generated by Django 3.0.6 on 2020-05-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderitem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ordernum',
            new_name='order',
        ),
    ]
