# Generated by Django 3.0.6 on 2020-05-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문 번호', 'verbose_name_plural': '주문 번호'},
        ),
    ]
